In [1]:
import pandas as pd

In [11]:
f = "../data/001_raw/vivienda01/comedor - sensor dennis - de 5 de noviembre al 22 de noviembre.csv"
comedor = pd.read_csv(f,index_col=1,parse_dates=True,dayfirst=False)
comedor

f = "../data/001_raw/vivienda01/dormitorio - sensor 20809036 - de 5 de noviembre al 22 de noviembre.csv"
dormitorio = pd.read_csv(f,index_col=1,parse_dates=True,dayfirst=False)
dormitorio

f = "../data/001_raw/vivienda01/sala - sensor richard - de 5 de noviembre al 22 de noviembre.csv"
sala = pd.read_csv(f,index_col=1,parse_dates=True,dayfirst=False)
sala

,#,Temperature (°C),RH (%),Dew Point (°C),Host Connected,End of File
Date-Time (Ecuador Standard Time),,,,,,
2024-11-05 08:42:31,1,NaN,NaN,NaN,Logged,NaN
2024-11-05 10:00:00,2,31.36,64.71,23.94,NaN,NaN
2024-11-05 10:05:00,3,31.63,64.88,24.24,NaN,NaN
2024-11-05 10:10:00,4,31.92,70.34,25.87,NaN,NaN
2024-11-05 10:15:00,5,32.07,63.28,24.23,NaN,NaN
...,...,...,...,...,...,...
2024-11-22 08:20:00,4878,24.16,87.01,21.89,NaN,NaN
2024-11-22 08:25:00,4879,24.18,87.20,21.95,NaN,NaN
2024-11-22 08:30:00,4880,24.19,86.76,21.88,NaN,NaN
2024-11-22 08:35:00,4881,24.19,86.44,21.81,NaN,NaN
2024-11-22 08:38:42,4882,NaN,NaN,NaN,Logged,Logged